apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: myapp-replicaset
  labels:
    app: myapp
    type: front-end
spec:
  template:
    metadata:
      name: myapp
      labels:
        name: myapp
        type: front-end
    spec:
      containers:
        - name: myapp
          image: nginx
  selector:
     matchLabels:
       type: front-end
  replicas: 6


