apiVersion: v1
kind: Pod
metadata:
  name: simple-webapp-color
  labels:
    name: webapp
spec:
  containers:
    - name: simple-webapp-color
      image: asad27/simple-webapp-color
      ports:
        - containerPort: 8080
      envFrom:
        - configMapRef:
            name: app-config