apiVersion: v1
kind: Pod
metadata:
  name: multi
  labels:
    app: frontend
spec:
  containers:
    - name: ubuntu-container
      image: ubuntu
      command: ["/bin/sh", "-c"]
      args:
        - "echo 'Hello, World'"
    - name: busybox-container
      image: busybox
      command: ["/bin/sh", "-c", "echo 'Initializing'"]
      env:
        - name: ENV_VAR_NAME
          value: "val1"
      volumeMounts:
        - name: data-volume
          mountPath: /host/path   # Specify the host path here
  volumes:
    - name: data-volume
      hostPath:
        path: /path/on/host       # Specify the host path here
